language: node_js

node_js:
  - 7
  - 6

script:
  - npm run test
  - npm run build

notifications:
  email:
    on_failure: change
  slack:
    secure: TCSWdu+B2Ir/gedvMUNzghk4Mk761K0orR4FaY+JkyUjYPjCNVw75wp75QEY+LwvBPd6CGzC6QtKcXlC9sdcwn2RDq+jl9MF2OShHdegboA6AVA1w3diDYoODzEvqDjK3jAoAvs9P5IinU3a8fokC2BQw3HmotIpNMvw9Fp1vcsLuLv/FFWexCJkV98F3NIpC2xpK0uUki/H1hun+M23PZkhlKFiBjsp0I1YeCBBDhqLDqkxvVFnKWATp/DI9YMTjg3d9ThqZo3fsg6Rxq/rywZa8vpvDbBfyi6XBTZXaxPcKJHpZwGpxkZQaUGWt22+dsfPFpocULM0g8otuYWCvmfFryyBeLwKT++dVYZWUd5ezB0IeryNBhsz5qC7cLiB56om55IYoylwvG8P8QorE0MaY+siDpZ4gGsvoslFaffohAopQJlP1VzgLW7BiOV3vad3jDXxbAqi7eRo+hD5Q4S2TJ6sczwBtNzQll2Yrr8t6KkdWchGBbDCYtcjH44C2b3tu0aNw/869o5X8OnQIoYJqO5u6UtRx0brcjduYVE9R/EAhXvi5xc/EotEFPqEH16FUjaUAZKDQqTpaUndWn4+rgU/enGwCaq8Omy7kxg+cDbaeM6rncGlGDm8grMGMHJYZHEln2ZDlMg9UlZqlNLq7cQIy/YhFlO+YynSIdk=

cache:
  yarn: true
  directories:
    - node_modules
